name: "CD(Docker): Publish dev image"

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 1 * * *"

jobs:
  ghcr:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/creatorhub:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
